### ISSUE TITLE
Cannot read properties of undefined (reading 'postcss')

### ISSUE THREAD

**Issue by mikwee** [flexdinesh/blogster#24]
Right after generating my Bubblegum site, I built it, only to get this error:
```
 error   Cannot read properties of undefined (reading 'postcss')
  File:
    D:\personal-site-astro\node_modules\@astrojs\tailwind\dist\index.js:78:22
  Code:
    77 |         const tailwindConfig = (userConfig == null ? void 0 : userConfig.value) ?? getDefaultTailwindConfig(config.srcDir);
    > 78 |         config.style.postcss.plugins.push(tailwindPlugin(tailwindConfig));
         |                      ^
      79 |         config.style.postcss.plugins.push(autoprefixerPlugin);
      80 |         if (applyBaseStyles) {
      81 |           injectScript("page-ssr", `import '@astrojs/tailwind/base.css';`);
  Stacktrace:
TypeError: Cannot read properties of undefined (reading 'postcss')
    at Object.astro:config:setup (file:///D:/personal-site-astro/node_modules/@astrojs/tailwind/dist/index.js:78:22)
    at async withTakingALongTimeMsg (file:///C:/Users/mikwee/AppData/Local/Yarn/Data/global/node_modules/astro/dist/integrations/index.js:15:18)
    at async runHookConfigSetup (file:///C:/Users/mikwee/AppData/Local/Yarn/Data/global/node_modules/astro/dist/integrations/index.js:69:7)
    at async AstroBuilder.setup (file:///C:/Users/mikwee/AppData/Local/Yarn/Data/global/node_modules/astro/dist/core/build/index.js:40:21)
    at async AstroBuilder.run (file:///C:/Users/mikwee/AppData/Local/Yarn/Data/global/node_modules/astro/dist/core/build/index.js:130:23)
    at async build (file:///C:/Users/mikwee/AppData/Local/Yarn/Data/global/node_modules/astro/dist/core/build/index.js:21:3)
    at async runCommand (file:///C:/Users/mikwee/AppData/Local/Yarn/Data/global/node_modules/astro/dist/cli/index.js:157:14)
    at async cli (file:///C:/Users/mikwee/AppData/Local/Yarn/Data/global/node_modules/astro/dist/cli/index.js:180:5)
```
Does anybody have an idea of what's going on? Thanks.

**Comment by pbrdebruijn** [comment]
This seems to be a tailwind related issue.

I've solved this issue by updating tailwind and @astrojs/tailwind in the package.json

```
"dependencies": {
   ...
    "@astrojs/tailwind": "^3.1.3",
    ...
    "tailwindcss": "^3.3.3",
    ...
  },
 
```

**Comment by mikwee** [comment]
It works well now, so I guess I can close this.
